"""message

Revision ID: 197f45c3777c
Revises: a1731b023384
Create Date: 2023-08-21 22:11:18.681352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197f45c3777c'
down_revision = 'a1731b023384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_character_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classes_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classes_id'], ['game_class.id'], name=op.f('fk_spell_classes_id_game_class')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classes_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_class_character_id_character')),
    sa.ForeignKeyConstraint(['classes_id'], ['game_class.id'], name=op.f('fk_character_class_classes_id_game_class')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spells_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_spell_selection_character_id_character')),
    sa.ForeignKeyConstraint(['spells_id'], ['spell.id'], name=op.f('fk_spell_selection_spells_id_spell')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('classes')
    op.drop_table('feats')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spell_selection')
    op.drop_table('character_class')
    op.drop_table('spell')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('game_class')
    # ### end Alembic commands ###
