"""fixed table errors

Revision ID: bb1d7f3fd875
Revises: 197f45c3777c
Create Date: 2023-08-21 22:58:26.267372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1d7f3fd875'
down_revision = '197f45c3777c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_class_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_character_class_classes_id_game_class', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_character_class_game_class_id_game_class'), 'game_class', ['game_class_id'], ['id'])
        batch_op.drop_column('classes_id')

    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_class_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_spell_classes_id_game_class', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_spell_game_class_id_game_class'), 'game_class', ['game_class_id'], ['id'])
        batch_op.drop_column('classes_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_spell_game_class_id_game_class'), type_='foreignkey')
        batch_op.create_foreign_key('fk_spell_classes_id_game_class', 'game_class', ['classes_id'], ['id'])
        batch_op.drop_column('game_class_id')

    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_character_class_game_class_id_game_class'), type_='foreignkey')
        batch_op.create_foreign_key('fk_character_class_classes_id_game_class', 'game_class', ['classes_id'], ['id'])
        batch_op.drop_column('game_class_id')

    # ### end Alembic commands ###
